<title><%= request.getAttribute("Title") %></title>

	<link href='<spring:url value="/resources/FIU/css/atlantis.min.css" />' rel="stylesheet">
	<link href='<spring:url value="/resources/FIU/css/bootstrap.min.css" />' rel="stylesheet">
	<link href='<spring:url value="/resources/FIU/css/fonts.min.css" />' rel="stylesheet">
	<link href='<spring:url value="/resources/FIU/css/Drag_and_Drop/jquery-ui.css" />'rel="stylesheet">
	<link href='<spring:url value="/resources/FIU/css/autocomplete.css" />'rel="stylesheet">
	<link href='<spring:url value="/resources/HDPAY/css/styles.css" />' rel="stylesheet">
	
	<script type="text/javascript" src='<spring:url value="/resources/FIU/sweetalert/dist/sweetalert.min.js"/>' ></script>
	<script type="text/javascript" src='<spring:url value="/resources/FIU/ajax/libs/jquery/3.2.1/jquery.min.js"/>' ></script>
	<script type="text/javascript" src='<spring:url value="/resources/FIU/js/plugin/webfont/webfont.min.js"/>' ></script>
	<script type="text/javascript" src='<spring:url value="/resources/FIU/js/core/bootstrap.min.js"/>' ></script>
	<script type="text/javascript" src='<spring:url value="/resources/FIU/js/atlantis.min.js"/>' ></script>
	<script type="text/javascript"src='<spring:url value="/resources/FIU/js/autocomplete.js"/>'></script>
	<script type="text/javascript"src='<spring:url value="/resources/FIU/js/autocomplete_ui.js"/>'></script>
	<script type="text/javascript" src='<spring:url value="/resources/FIU/js/core/popper.min.js"/>' ></script>	
	<script type="text/javascript" src='<spring:url value="/resources/FIU/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"/>' ></script>
	<script type="text/javascript" src='<spring:url value="/resources/FIU/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"/>' ></script>	
	<script type="text/javascript" src='<spring:url value="/resources/FIU/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"/>' ></script>
	<script type="text/javascript"src='<spring:url value="/resources/FIU/js/plugin/jspdf/jspdf.min.js"/>'></script>
	<script type="text/javascript"src='<spring:url value="/resources/FIU/js/plugin/jspdf/jspdf.plugin.autotable.min.js"/>'></script>
	<script type="text/javascript"src='<spring:url value="/resources/FIU/Validations/Interpolation/inter.js" />'></script>

<style>
	.form-control:disabled, .form-control[readonly] {
    background: #fff!important;
    border-color: #7e7c7c!important;
}

</style>

</head>